name: 'Setup Bun'
description: 'Setup Bun environment and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
