name: NPM Publish

on:
  workflow_run:
    workflows: ['Build Binaries']
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Publish to NPM
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
