name: NPM Publish

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run quality checks
        run: bun run check

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
